timeout: "3600s"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # --------------------------------------------------
  # 1️⃣ Clone repo
  # --------------------------------------------------
  - name: "gcr.io/cloud-builders/git"
    args:
      - clone
      - https://github.com/skillmatrix24/web2native-android-temp.git
      - app

  # --------------------------------------------------
  # 2️⃣ Build APK (Android SDK already present)
  # --------------------------------------------------
  - name: "gcr.io/android-build-tools/android-30"
    dir: "app"
    env:
      - GRADLE_USER_HOME=/workspace/.gradle
    args:
      - bash
      - -c
      - |
        chmod +x ./gradlew
        ./gradlew clean assembleRelease

# --------------------------------------------------
# 3️⃣ Upload APK
# --------------------------------------------------
artifacts:
  objects:
    location: "gs://studio-7777713866-cb01e.firebasestorage.app/apks/"
    paths:
      - "app/app/build/outputs/apk/release/*.apk"
