steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/skillmatrix24/web2native-android-temp.git']

  - name: 'gcr.io/cloud-builders/gradle'
    dir: 'web2native-android-template'
    args: ['assembleRelease']

artifacts:
  objects:
    location: 'gs://studio-7777713866-cb01e.firebasestorage.app/apks/'
    paths:
      - 'web2native-android-template/app/build/outputs/apk/release/app-release-unsigned.apk'
