timeout: "3600s"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # --------------------------------------------------
  # 1️⃣ Build APK directly from uploaded source
  # --------------------------------------------------
  - name: "gcr.io/android-build-tools/android-30"
    dir: "."
    env:
      - GRADLE_USER_HOME=/workspace/.gradle
    args:
      - bash
      - -c
      - |
        chmod +x ./gradlew
        ./gradlew clean assembleRelease

# --------------------------------------------------
# 2️⃣ Upload APK to Firebase Storage bucket
# --------------------------------------------------
artifacts:
  objects:
    location: "gs://studio-7777713866-cb01e.firebasestorage.app/apks/"
    paths:
      - "app/build/outputs/apk/release/*.apk"
