steps:
  # 1ï¸âƒ£ Clone repo
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/skillmatrix24/web2native-android-temp.git

  # 2ï¸âƒ£ Build SIGNED APK + AAB
  - name: ghcr.io/cirruslabs/android-sdk:36
    dir: web2native-android-temp
    entrypoint: bash
    secretEnv:
      - KEYSTORE_BASE64
      - KEYSTORE_PASSWORD
      - KEY_ALIAS
      - KEY_PASSWORD
    args:
      - -c
      - |
        set -e
        chmod +x ./gradlew

        echo "ðŸ“‚ Writing keystore file (CI)..."
        mkdir -p keystore
        printf "%s" "$$KEYSTORE_BASE64" | base64 -d > keystore/web2native-release.jks

        echo "ðŸš€ Building RELEASE APK..."
        ./gradlew clean assembleRelease

        echo "ðŸš€ Building RELEASE AAB..."
        ./gradlew bundleRelease

availableSecrets:
  secretManager:
    - versionName: projects/studio-7777713866-cb01e/secrets/KEYSTORE_BASE64/versions/latest
      env: KEYSTORE_BASE64
    - versionName: projects/studio-7777713866-cb01e/secrets/KEYSTORE_PASSWORD/versions/latest
      env: KEYSTORE_PASSWORD
    - versionName: projects/studio-7777713866-cb01e/secrets/KEY_ALIAS/versions/latest
      env: KEY_ALIAS
    - versionName: projects/studio-7777713866-cb01e/secrets/KEY_PASSWORD/versions/latest
      env: KEY_PASSWORD

artifacts:
  objects:
    location: gs://studio-7777713866-cb01e.firebasestorage.app/apks/
    paths:
      - web2native-android-temp/app/build/outputs/apk/release/app-release.apk
      - web2native-android-temp/app/build/outputs/bundle/release/app-release.aab

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
