timeout: "3600s"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/android-build-tools/android-36"
    entrypoint: bash
    args:
      - -c
      - |
        set -e

        chmod +x ./gradlew
        ./gradlew clean assembleRelease

artifacts:
  objects:
    location: "gs://studio-7777713866-cb01e.firebasestorage.app/apks/"
    paths:
      - "app/build/outputs/apk/release/*.apk"
