steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - https://github.com/skillmatrix24/web2native-android-temp.git

  - name: ghcr.io/cirruslabs/android-sdk:36
    dir: web2native-android-temp
    entrypoint: bash
    secretEnv:
      - KEYSTORE_BASE64
      - KEYSTORE_PASSWORD
      - KEY_ALIAS
      - KEY_PASSWORD
    args:
      - -c
      - |
        set -e
        chmod +x ./gradlew

        echo "📂 Writing keystore..."
        mkdir -p app/keystore
        echo "$KEYSTORE_BASE64" | base64 -d > app/keystore/web2native-release.jks

        echo "🔐 Writing keystore.properties"
        cat <<EOF > keystore.properties
storeFile=app/keystore/web2native-release.jks
storePassword=$KEYSTORE_PASSWORD
keyAlias=$KEY_ALIAS
keyPassword=$KEY_PASSWORD
EOF

        ./gradlew clean assembleRelease
        ./gradlew bundleRelease

availableSecrets:
  secretManager:
    - versionName: projects/studio-7777713866-cb01e/secrets/KEYSTORE_BASE64/versions/latest
      env: KEYSTORE_BASE64
    - versionName: projects/studio-7777713866-cb01e/secrets/KEYSTORE_PASSWORD/versions/latest
      env: KEYSTORE_PASSWORD
    - versionName: projects/studio-7777713866-cb01e/secrets/KEY_ALIAS/versions/latest
      env: KEY_ALIAS
    - versionName: projects/studio-7777713866-cb01e/secrets/KEY_PASSWORD/versions/latest
      env: KEY_PASSWORD

artifacts:
  objects:
    location: gs://studio-7777713866-cb01e.firebasestorage.app/apks/
    paths:
      - web2native-android-temp/app/build/outputs/apk/release/app-release.apk
      - web2native-android-temp/app/build/outputs/bundle/release/app-release.aab

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
